'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { RefreshCw, ExternalLink } from 'lucide-react';

interface FileNode {
  name: string;
  type: 'file' | 'folder';
  language?: string;
  content?: string;
  children?: FileNode[];
}

interface PreviewPanelProps {
  files: FileNode[];
  vfs: Record<string, { content: string; language: string }>;
  manifest: any;
}

export function PreviewPanel({ files, vfs, manifest }: PreviewPanelProps) {
  const [isRefreshing, setIsRefreshing] = useState(false);

  const handleRefresh = () => {
    setIsRefreshing(true);
    setTimeout(() => setIsRefreshing(false), 1000);
  };

  const generatePreview = () => {
    // First check if manifest has previewFile
    if (manifest?.previewFile && vfs[manifest.previewFile]) {
      return vfs[manifest.previewFile].content;
    }
    
    // Fallback: find index.html
    const findFileByName = (nodes: FileNode[], name: string): FileNode | null => {
      for (const node of nodes) {
        if (node.type === 'file' && node.name === name) {
          return node;
        }
        if (node.children) {
          const found = findFileByName(node.children, name);
          if (found) return found;
        }
      }
      return null;
    };

    const htmlFile = findFileByName(files, 'index.html');
    if (htmlFile && htmlFile.content) {
      return htmlFile.content;
    }

    const reactFiles = files.filter(f => f.name.endsWith('.tsx') || f.name.endsWith('.jsx'));
    if (reactFiles.length > 0) {
      return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Preview</title>
  <script src="https://unpkg.com/react@18/umd/react.development.js"></script>
  <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      margin: 0;
      padding: 20px;
      background: #f5f5f5;
    }
    .container {
      max-width: 800px;
      margin: 0 auto;
      background: white;
      padding: 32px;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
  </style>
</head>
<body>
  <div id="root"></div>
  <script type="text/babel">
    const { useState } = React;

    function App() {
      return (
        <div className="container">
          <h1 style={{ fontSize: '2em', marginBottom: '0.5em' }}>Generated Artifact Preview</h1>
          <p style={{ color: '#666' }}>This is a live preview of the generated artifact.</p>
          <div style={{ marginTop: '20px', padding: '16px', background: '#f0f0f0', borderRadius: '4px' }}>
            <strong>Files in project:</strong>
            <ul style={{ marginTop: '8px', marginBottom: 0 }}>
              ${reactFiles.map(f => `<li key="${f.name}">${f.name}</li>`).join('')}
            </ul>
          </div>
        </div>
      );
    }

    ReactDOM.createRoot(document.getElementById('root')).render(<App />);
  </script>
</body>
</html>`;
    }

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Preview</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      margin: 0;
      padding: 40px;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .card {
      background: white;
      padding: 40px;
      border-radius: 12px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
      max-width: 500px;
      text-align: center;
    }
    h1 {
      margin: 0 0 16px 0;
      color: #333;
    }
    p {
      color: #666;
      line-height: 1.6;
    }
  </style>
</head>
<body>
  <div class="card">
    <h1>🎨 Artifact Preview</h1>
    <p>This artifact was generated by Orion OS. Select files from the explorer to see their contents in the Code tab.</p>
  </div>
</body>
</html>`;
  };

  const previewContent = generatePreview();

  return (
    <div className="h-full flex flex-col bg-[#0d1117]">
      <div className="h-10 bg-[#161b22] border-b border-[#30363d] flex items-center justify-between px-4">
        <div className="flex items-center gap-2">
          <span className="text-white text-sm font-medium">Live Preview</span>
          <span className="text-[#8b949e] text-xs">iframe</span>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleRefresh}
            className="p-1.5 hover:bg-[#21262d] rounded text-[#8b949e] hover:text-white transition-colors"
            title="Refresh Preview"
          >
            <RefreshCw className={`w-4 h-4 ${isRefreshing ? 'animate-spin' : ''}`} />
          </button>
          <button
            className="p-1.5 hover:bg-[#21262d] rounded text-[#8b949e] hover:text-white transition-colors"
            title="Open in New Tab"
            onClick={() => {
              const blob = new Blob([previewContent], { type: 'text/html' });
              const url = URL.createObjectURL(blob);
              window.open(url, '_blank');
            }}
          >
            <ExternalLink className="w-4 h-4" />
          </button>
        </div>
      </div>
      <div className="flex-1 bg-white">
        <iframe
          srcDoc={previewContent}
          className="w-full h-full border-0"
          title="Artifact Preview"
          sandbox="allow-scripts allow-same-origin"
        />
      </div>
    </div>
  );
}
